SELECT
    prog.ACAD_PROG_CODE AS academic_program_code,
    COUNT(DISTINCT f.SCHOLAR_WID) AS student_count
FROM OBIA_DW.W_SIA_TERM_ENRLMT_F f
LEFT JOIN OBIA_DW.W_SIA_ACAD_PROG_D prog
    ON f.PRI_ACAD_PROG_WID = prog.ROW_WID
WHERE f.DELETE_FLG = 'N'
  AND f.X_TERM_ENROLLED_FLAG = 'Y'
  AND f.TERM_WID IN (
      SELECT t.ROW_WID
      FROM OBIA_DW.W_SIA_TERM_D t
      WHERE t.TERM_CODE = '20263'
  )
  AND prog.ACAD_PROG_CODE NOT IN ('__NOT_APPLICABLE__', '__UNASSIGNED__')
GROUP BY prog.ACAD_PROG_CODE
ORDER BY student_count DESC
FETCH FIRST 100 ROWS ONLY
